apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-php-deployment
  labels:
    app: ecommerce-php-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: ecommerce-php-deployment
  template:
    metadata:
      labels:
        app: ecommerce-php-deployment
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          env:
            - name: PMA_HOST
              value: "4.tcp.ngrok"
            - name: PMA_PORT
              value: "10602"
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
          ports:
            - containerPort: 3306
