apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elcampo-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: "bramen.org"
      http:
        paths:

        - pathType: Prefix
          path: /
          backend:
            service:
              name: ecommerce
              port:
                number: 80

        - pathType: Prefix
          path: /api
          backend:
            service:
              name: api
              port:
                number: 80

        - pathType: Prefix
          path: /hello
          backend:
            service:
              name: hello-one
              port:
                number: 80
