apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      containers:
        - name: api-cultivos
          image: 376288839410.dkr.ecr.us-east-1.amazonaws.com/fastapi-assetsment
          env:
            - name: POSTGRES_URI
              value: "postgresql://bramen:bramen@0.tcp.ngrok.io:17502/api"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-secret
