name: Despligue IoT


on:  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo '${{ secrets.KUBECONFIG }}' | base64 --decode > ${HOME}/.kube/config

      - name: Deploy to K8s
        run: ls -l
        working-directory: ./.k8s/iot

      - name: Deploy to K8s
        run: kubectl apply -f .
        working-directory: ./.k8s/iot