name: Arrancar Servidor ThingsBoard 🟢

on:
  workflow_dispatch:


jobs:
  deploy:
    name: Terraform settings
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./iot
    env:
      TF_VAR_linode_token: ${{ secrets.TF_VAR_LINODE_TOKEN }}
      TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_SSH_PUBLIC_KEY }}
      TF_VAR_ssh_private_key: ${{ secrets.TF_VAR_SSH_PRIVATE_KEY }}
      TF_VAR_root_password: ${{ secrets.TF_VAR_ROOT_PASSWORD }}
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

    steps:
    - name: Install terraform
      uses: hashicorp/setup-terraform@v3

    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Terraform version
      run: terraform version

    - name: Terraform init
      run: terraform init

    - name: Terraform validate
      run: terraform validate

    - name: Terraform plan
      run: terraform plan

    - name: Terraform apply
      run: terraform apply -auto-approve -no-color > /dev/null

    - name: Imprimir salidad
      run: terraform output
